apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-b-deployment
  name: service-b-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b-deployment
  template:
    metadata:
      labels:
        app: service-b-deployment
    spec:
      containers:
      - image: abhishekf5/demoservice-b:v  # Update with the actual version/tag
        name: service-b
        imagePullPolicy: Always
        ports:
        - containerPort: 3002  # Port where service-b listens
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        command: ["stress"]  # Start stress testing in the main container
        args: ["--cpu", "2", "--timeout", "30s"]  # Adjust parameters as needed
        env:
        - name: OTEL_EXPORTER_JAEGER_ENDPOINT
          value: "http://jaeger-collector.tracing:14268/api/traces"
        - name: SERVICE_A_URI
          value: "http://service-a.default.svc.cluster.local:3001"  # URI to access service-a
      initContainers:
      - name: init-pod
        image: busybox
        command: ['sh', '-c']
        args: ["until nc -z service-a 3001; do echo waiting for service-a; sleep 2; done"]
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"

