apiVersion: v1
kind: Service
metadata:
  name: service-a  # This name will be used by service-b to access it
spec:
  selector:
    app: service-a-deployment
  ports:
    - protocol: TCP
      port: 3001  # Port to expose
      targetPort: 3001  # Port on the container

