apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-deployment
  labels:
    app: service-b-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b-deployment
  template:
    metadata:
      labels:
        app: service-b-deployment
    spec:
      initContainers:
      - name: wait-for-service-a
        image: busybox:latest
        command: ['sh', '-c', 'until nc -z service-a.default.svc.cluster.local 3001; do echo waiting for service-a; sleep 2; done']
      containers:
      - name: service-b
        image: abhishekf5/demoservice-b:v
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        env:
        - name: OTEL_EXPORTER_JAEGER_ENDPOINT
          value: "http://jaeger-collector.tracing:14268/api/traces"
        command: ['sh', '-c', 'echo "Service B is starting..."; sleep 3600']  # Keeps the container running for testing
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  selector:
    app: service-b-deployment
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002

